language: ruby

# http://www.redmine.org/projects/redmine/wiki/RedmineInstall
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

env:
  - REDMINE_REPOS=4.0-stable
  - REDMINE_REPOS=4.1-stable

gemfile:
  - $REDMINE_PATH/Gemfile

before_install:
  - export PLUGIN_NAME=redmine_send_issue_reply_email
  - export DB=sqlite
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - export TESTSPACE=`pwd`/testspace/
  - export REDMINE_PATH=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - git clone git://github.com/redmine/redmine.git $REDMINE_PATH
  - git checkout -b $REDMINE_REPOS origin/$REDMINE_REPOS 
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp test/database.travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - RUBYOPT=-W0 bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME

branches:
  only:
    - master
